language: csharp
solution: NameSorter.sln
install:
 - sudo apt-get install nunit-console
 - nuget restore NameSorter.sln
script:
- xbuild /p:Configuration=Release NameSorter.sln
- nunit-console ./NameSorterTests/bin/Debug/NameSorterTests.dll